
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class addCourseForm extends javax.swing.JFrame {

    Course c = new Course();
    public addCourseForm() 
    {
        initComponents();
        //jTextFieldCourseLabel.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerHours = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCourseLabel = new javax.swing.JTextField();
        jButtonAddCourse = new javax.swing.JButton();
        jButtonRemoveCourse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 904));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Hours:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 255, 70, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Label:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 175, 70, 20));

        jSpinnerHours.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSpinnerHours.setModel(new javax.swing.SpinnerNumberModel(3, 3, 300, 1));
        jSpinnerHours.setPreferredSize(new java.awt.Dimension(6, 28));
        jPanel1.add(jSpinnerHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 130, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 904));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Hours:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 255, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Label:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 175, 70, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setText("Add Course");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 180, -1));

        jTextFieldCourseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldCourseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 200, -1));

        jButtonAddCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAddCourse.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\plus.png")); // NOI18N
        jButtonAddCourse.setText("Add");
        jButtonAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCourseActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 130, 50));

        jButtonRemoveCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRemoveCourse.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\cancel.png")); // NOI18N
        jButtonRemoveCourse.setText("Cancel");
        jButtonRemoveCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveCourseActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRemoveCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 150, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 710));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCourseActionPerformed
        if(!c.courseExist(jTextFieldCourseLabel.getText()))
      {
        String label  = jTextFieldCourseLabel.getText();
        int hours = Integer.valueOf(jSpinnerHours.getValue().toString());
        Course c = new Course();
        c.insertUpdateDeleteCourse('i',null,label, hours);
        MainForm.LabeCourseCount.setText("Course Count="+Integer.toString(MyFunction.countData("Courses")));
        try
        {
        manageCourses.jTableCourses.setModel(new DefaultTableModel(null,new Object[]{"Id","Coursename","Hours"}));
        c.fillCourseJTable(manageCourses.jTableCourses); 
        }
        catch(Exception ex)
        { 
            System.out.println(ex.getMessage());
        }
     }
        else
        {
                    JOptionPane.showMessageDialog(null,"Course Already Exists");
                    jTextFieldCourseLabel.setText("");
                    jSpinnerHours.setValue(3);
        }
        
        
    }//GEN-LAST:event_jButtonAddCourseActionPerformed

    private void jButtonRemoveCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveCourseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonRemoveCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCourseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCourse;
    private javax.swing.JButton jButtonRemoveCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerHours;
    private javax.swing.JTextField jTextFieldCourseLabel;
    // End of variables declaration//GEN-END:variables
}
