

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class addScore extends javax.swing.JFrame {

    /**
     * Creates new form addScore
     */
    Course c = new Course();
    Student std = new Student();
    DefaultTableModel model;
    Score sc = new Score();
    public addScore() {
        initComponents();
        c.fillComboBox(jComboBoxCourse);
        std.fillStudentJtable(jTableScoreTable,"");
        
       hideColumn(6);
       hideColumn(5);
       hideColumn(4);
       hideColumn(3);
       
       model = (DefaultTableModel)jTableScoreTable.getModel();
       jTableScoreTable.setRowHeight(40);
        jTableScoreTable.setGridColor(new Color(102,204,255));
       jTableScoreTable.setShowGrid(true);
        jTableScoreTable.setSelectionBackground(Color.BLACK);
    }
    
   private void hideColumn(int colIndex)
   {
       TableColumn col = jTableScoreTable.getColumnModel().getColumn(colIndex);
       col.setMaxWidth(0);
       col.setMinWidth(0);
       col.setPreferredWidth(0);
       
     
   } 

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneladdScore = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldScore = new javax.swing.JTextField();
        jButtonCancelScore = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldScoreStdId = new javax.swing.JTextField();
        jButtonAddScore = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableScoreTable = new javax.swing.JTable();
        jComboBoxCourse = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDescription = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPaneladdScore.setBackground(new java.awt.Color(255, 204, 102));
        jPaneladdScore.setPreferredSize(new java.awt.Dimension(1280, 904));
        jPaneladdScore.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Score:");
        jPaneladdScore.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 225, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Course Id:");
        jPaneladdScore.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 110, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setText("Add Score");
        jPaneladdScore.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 160, -1));

        jTextFieldScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPaneladdScore.add(jTextFieldScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 200, -1));

        jButtonCancelScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancelScore.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\cancel.png")); // NOI18N
        jButtonCancelScore.setText("Cancel");
        jButtonCancelScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelScoreActionPerformed(evt);
            }
        });
        jPaneladdScore.add(jButtonCancelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 160, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Student Id:");
        jPaneladdScore.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 120, 20));

        jTextFieldScoreStdId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPaneladdScore.add(jTextFieldScoreStdId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 200, -1));

        jButtonAddScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAddScore.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\plus.png")); // NOI18N
        jButtonAddScore.setText("Add");
        jButtonAddScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddScoreActionPerformed(evt);
            }
        });
        jPaneladdScore.add(jButtonAddScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 130, 50));

        jTableScoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FirstName", "LastName", "Sex", "BirthDate", "Phone", "Address"
            }
        ));
        jTableScoreTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableScoreTableMouseClicked(evt);
            }
        });
        jTableScoreTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableScoreTableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableScoreTable);

        jPaneladdScore.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 680, 610));

        jComboBoxCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCourseActionPerformed(evt);
            }
        });
        jPaneladdScore.add(jComboBoxCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 155, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Description:");
        jPaneladdScore.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 130, 40));

        jTextFieldDescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPaneladdScore.add(jTextFieldDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPaneladdScore, javax.swing.GroupLayout.PREFERRED_SIZE, 1380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPaneladdScore, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelScoreActionPerformed
        
          this.dispose();
//        if(jTextFieldScoreStdId.getText().equals(""))
//        {
//            JOptionPane.showMessageDialog(null,"Course not selected");
//        }
//        else
//        {
//            int id = Integer.valueOf(jTextFieldScoreStdId.getText());
//            c.insertUpdateDeleteCourse('d', id, null, null);
//            manageCourses.jTableCourses.setModel(new DefaultTableModel(null,new Object[]{"Id","Coursename","Hours"}));
//            MainForm.LabeCourseCount.setText("Course Count = " + Integer.toString(MyFunction.countData("Courses")));
//            c.fillCourseJTable(manageCourses.jTableCourses);
//            jTextFieldScoreStdId.setText("");
//            jTextFieldScore.setText("");
//            jSpinnerHours.setValue(3);
    }//GEN-LAST:event_jButtonCancelScoreActionPerformed

    private void jButtonAddScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddScoreActionPerformed
      
        int stdId = Integer.valueOf(jTextFieldScoreStdId.getText());
        int crsId = Integer.valueOf(c.getCourseId(jComboBoxCourse.getSelectedItem().toString()));
        double score = Double.valueOf(jTextFieldScore.getText());
        sc.insertUpdateDeleteScore('i', stdId, crsId,score,jTextFieldDescription.getText());
        try
        {
            editDeleteScore.jTableScoreTable.setModel(new DefaultTableModel(null,new Object[]{"Student_ID","Course_ID","Score","Description"}));
            sc.fillScoreJTable(editDeleteScore.jTableScoreTable);
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonAddScoreActionPerformed

    private void jTableScoreTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableScoreTableMouseClicked
        int rowIndex = jTableScoreTable.getSelectedRow();
        jTextFieldScoreStdId.setText(jTableScoreTable.getValueAt(rowIndex,0).toString());
        
        
//        rowIndex = jTableScoreTable.getSelectedRow();
//        DefaultTableModel model = (DefaultTableModel)jTableScoreTable.getModel();
//        jTextFieldID.setText(model.getValueAt(rowIndex,0).toString());
//        jTextFieldFname.setText(model.getValueAt(rowIndex,1).toString());
//        jTextFieldLname.setText(model.getValueAt(rowIndex,2).toString());
//        jTextFieldPhone.setText(model.getValueAt(rowIndex,5).toString());
//        jTextFieldBirthDate.setText(model.getValueAt(rowIndex,4).toString());
//        jTextAreaAddress.setText(model.getValueAt(rowIndex,6).toString());
//        //jTextFieldValueFind.setText(model.getValueAt(rowIndex, 0).toString());
    }//GEN-LAST:event_jTableScoreTableMouseClicked

    private void jTableScoreTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableScoreTableKeyReleased
//        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN)
//        {
//            rowIndex = jTableScoreTable.getSelectedRow();
//            jTextFieldID.setText(model.getValueAt(rowIndex,0).toString());
//            jTextFieldFname.setText(model.getValueAt(rowIndex,1).toString());
//            jTextFieldLname.setText(model.getValueAt(rowIndex,2).toString());
//            jTextFieldPhone.setText(model.getValueAt(rowIndex,5).toString());
//            jTextFieldBirthDate.setText(model.getValueAt(rowIndex,4).toString());
//            jTextAreaAddress.setText(model.getValueAt(rowIndex,6).toString());
//
//            if(model.getValueAt(rowIndex,3).toString().equals("Male"))
//            {
//                jRadioButtonMale.setSelected(true);
//                jRadioButtonFemale.setSelected(false);
//            }
//            else
//            {
//                jRadioButtonFemale.setSelected(true);
//                jRadioButtonMale.setSelected(false);
//            }
//        }
    }//GEN-LAST:event_jTableScoreTableKeyReleased

    private void jComboBoxCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addScore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddScore;
    private javax.swing.JButton jButtonCancelScore;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPaneladdScore;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTableScoreTable;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldScore;
    private javax.swing.JTextField jTextFieldScoreStdId;
    // End of variables declaration//GEN-END:variables
}

