
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        LabelWelcome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabeCourseCount = new javax.swing.JLabel();
        PanelStudentCount = new javax.swing.JPanel();
        MainFormLabelStudentCount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemManage = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAddCourse = new javax.swing.JMenuItem();
        jMenuCourseManage = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAddScore = new javax.swing.JMenuItem();
        jMenuItemManageScore = new javax.swing.JMenuItem();
        jMenuItemShowScore = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelWelcome.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        LabelWelcome.setText("Welcome<####>");
        jPanel2.add(LabelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 330, -1));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(310, 99));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabeCourseCount.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        LabeCourseCount.setForeground(new java.awt.Color(255, 255, 255));
        LabeCourseCount.setText("Courses Count = ");
        jPanel1.add(LabeCourseCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 180, 330, 170));

        PanelStudentCount.setBackground(new java.awt.Color(102, 153, 255));
        PanelStudentCount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainFormLabelStudentCount.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        MainFormLabelStudentCount.setForeground(new java.awt.Color(255, 255, 255));
        MainFormLabelStudentCount.setText("Students Count = ");
        PanelStudentCount.add(MainFormLabelStudentCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 300, -1));

        jPanel2.add(PanelStudentCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 330, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\icons8-school-64.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 780));

        jMenu4.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\icons8-people-48.png")); // NOI18N
        jMenu4.setText("Student");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem2.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\plus.png")); // NOI18N
        jMenuItem2.setText("Add");
        jMenuItem2.setToolTipText("Add Student");
        jMenuItem2.setPreferredSize(new java.awt.Dimension(90, 50));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItemManage.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\edit.png")); // NOI18N
        jMenuItemManage.setText("Manage ");
        jMenuItemManage.setToolTipText("Manage existing student");
        jMenuItemManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemManage);

        jMenuBar1.add(jMenu4);

        jMenu1.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\icons8-course-48.png")); // NOI18N
        jMenu1.setText("Course");

        jMenuItemAddCourse.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\plus.png")); // NOI18N
        jMenuItemAddCourse.setText("Add");
        jMenuItemAddCourse.setToolTipText("Add Course");
        jMenuItemAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddCourseActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAddCourse);

        jMenuCourseManage.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\edit.png")); // NOI18N
        jMenuCourseManage.setText("Manage");
        jMenuCourseManage.setToolTipText("Manage Existing course");
        jMenuCourseManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCourseManageActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCourseManage);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\icons8-scoreboard-48.png")); // NOI18N
        jMenu2.setText("Scores");

        jMenuItemAddScore.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\plus.png")); // NOI18N
        jMenuItemAddScore.setText("Add");
        jMenuItemAddScore.setToolTipText("Add Score");
        jMenuItemAddScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddScoreActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAddScore);

        jMenuItemManageScore.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\edit.png")); // NOI18N
        jMenuItemManageScore.setText("Manage");
        jMenuItemManageScore.setToolTipText("Manage Scores");
        jMenuItemManageScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageScoreActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemManageScore);

        jMenuItemShowScore.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\icons8-show-property-48.png")); // NOI18N
        jMenuItemShowScore.setText("Show scores");
        jMenuItemShowScore.setToolTipText("Show all scores");
        jMenuItemShowScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemShowScoreActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemShowScore);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
                    AddStudent addStudent = new AddStudent();
                    addStudent.setVisible(true);
                    addStudent.pack();
                    addStudent.setLocationRelativeTo(null);
                    addStudent.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageActionPerformed
        // TODO add your handling code here:
                     ManageStudentsForm manageStudent = new ManageStudentsForm();
                    manageStudent.setVisible(true);
                    manageStudent.pack();
                    manageStudent.setLocationRelativeTo(null);
                    manageStudent.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemManageActionPerformed

    private void jMenuItemAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCourseActionPerformed
        // TODO add your handling code here:
                     addCourseForm addCourse = new addCourseForm();
                    addCourse.setVisible(true);
                    addCourse.pack();
                    addCourse.setLocationRelativeTo(null);
                    addCourse.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemAddCourseActionPerformed

    private void jMenuCourseManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCourseManageActionPerformed
        // TODO add your handling code here:
        manageCourses mc = new manageCourses();
        mc.setVisible(true);
        mc.pack();
        mc.setLocationRelativeTo(null);
        mc.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuCourseManageActionPerformed

    private void jMenuItemManageScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageScoreActionPerformed
         
         editDeleteScore eds = new editDeleteScore();
         eds.setVisible(true);
         eds.pack();
         eds.setLocationRelativeTo(null);
         eds.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemManageScoreActionPerformed

    private void jMenuItemAddScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddScoreActionPerformed
       addScore s = new addScore();
       s.setVisible(true);
       s.pack();
       s.setLocationRelativeTo(null);
       s.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemAddScoreActionPerformed

    private void jMenuItemShowScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemShowScoreActionPerformed
        
                showScores as = new showScores();
                as.setVisible(true);
                as.pack();
                as.setLocationRelativeTo(null);
                as.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemShowScoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LabeCourseCount;
    public static javax.swing.JLabel LabelWelcome;
    public static javax.swing.JLabel MainFormLabelStudentCount;
    private javax.swing.JPanel PanelStudentCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCourseManage;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAddCourse;
    private javax.swing.JMenuItem jMenuItemAddScore;
    private javax.swing.JMenuItem jMenuItemManage;
    private javax.swing.JMenuItem jMenuItemManageScore;
    private javax.swing.JMenuItem jMenuItemShowScore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
