
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class manageCourses extends javax.swing.JFrame {
    
    Course c = new Course();
    DefaultTableModel model;
    
    public manageCourses() {
        initComponents();
        c.fillCourseJTable(jTableCourses);
        jTableCourses.setRowHeight(40);
        jTableCourses.setGridColor(new Color(102,204,255));
        jTableCourses.setShowGrid(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelManageScore = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldManageCourseLabel = new javax.swing.JTextField();
        jButtonEditCourse = new javax.swing.JButton();
        jButtonDeleteCourse = new javax.swing.JButton();
        jSpinnerHours = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCourses = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldManageCourseId = new javax.swing.JTextField();
        jButtonAddCourse1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelManageScore.setBackground(new java.awt.Color(255, 255, 153));
        jPanelManageScore.setPreferredSize(new java.awt.Dimension(1280, 904));
        jPanelManageScore.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Hours:");
        jPanelManageScore.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 255, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Course:");
        jPanelManageScore.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 185, 80, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setText("Manage Course");
        jPanelManageScore.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 250, -1));

        jTextFieldManageCourseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelManageScore.add(jTextFieldManageCourseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 200, -1));

        jButtonEditCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEditCourse.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\icons8-maintenance-48.png")); // NOI18N
        jButtonEditCourse.setText("Edit");
        jButtonEditCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditCourseActionPerformed(evt);
            }
        });
        jPanelManageScore.add(jButtonEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 140, 50));

        jButtonDeleteCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDeleteCourse.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\cancel.png")); // NOI18N
        jButtonDeleteCourse.setText("Remove");
        jButtonDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCourseActionPerformed(evt);
            }
        });
        jPanelManageScore.add(jButtonDeleteCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 160, 50));

        jSpinnerHours.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSpinnerHours.setModel(new javax.swing.SpinnerNumberModel(3, 3, 300, 1));
        jSpinnerHours.setPreferredSize(new java.awt.Dimension(6, 28));
        jPanelManageScore.add(jSpinnerHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 130, -1));

        jTableCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Coursename", "Hours"
            }
        ));
        jTableCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCoursesMouseClicked(evt);
            }
        });
        jTableCourses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableCoursesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCourses);

        jPanelManageScore.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 80, 570, 480));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Id:");
        jPanelManageScore.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 125, 40, 20));

        jTextFieldManageCourseId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelManageScore.add(jTextFieldManageCourseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 200, -1));

        jButtonAddCourse1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAddCourse1.setIcon(new javax.swing.ImageIcon("D:\\Java_Files\\NetBeans\\Images\\plus.png")); // NOI18N
        jButtonAddCourse1.setText("Add");
        jButtonAddCourse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCourse1ActionPerformed(evt);
            }
        });
        jPanelManageScore.add(jButtonAddCourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 130, 50));

        getContentPane().add(jPanelManageScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditCourseActionPerformed
        if(jTextFieldManageCourseLabel.getText().equals(""))
        {
           JOptionPane.showMessageDialog(null,"Couse not selected");
        }
        else
        {
        int id = Integer.valueOf(jTextFieldManageCourseId.getText());
         String  label = jTextFieldManageCourseLabel.getText();
         int hours = Integer.valueOf(jSpinnerHours.getValue().toString());
         c.insertUpdateDeleteCourse('u',id,label,hours);
         MainForm.LabeCourseCount.setText("Course Count = " + Integer.toString(MyFunction.countData("Courses")));
         manageCourses.jTableCourses.setModel(new DefaultTableModel(null,new Object[]{"Id","Coursename","Hours"}));
         c.fillCourseJTable(manageCourses.jTableCourses);
         JOptionPane.showMessageDialog(null,"Course Edited");
        }

    }//GEN-LAST:event_jButtonEditCourseActionPerformed

    private void jButtonDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCourseActionPerformed
        // TODO add your handling code here:
        if(jTextFieldManageCourseId.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Course not selected");
        }
        else
        {
            int id = Integer.valueOf(jTextFieldManageCourseId.getText());
            c.insertUpdateDeleteCourse('d', id, null, null);
            manageCourses.jTableCourses.setModel(new DefaultTableModel(null,new Object[]{"Id","Coursename","Hours"}));
            MainForm.LabeCourseCount.setText("Course Count = " + Integer.toString(MyFunction.countData("Courses")));
            c.fillCourseJTable(manageCourses.jTableCourses);
            jTextFieldManageCourseId.setText("");
            jTextFieldManageCourseLabel.setText("");
            jSpinnerHours.setValue(3);
        }
    }//GEN-LAST:event_jButtonDeleteCourseActionPerformed

    private void jButtonAddCourse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCourse1ActionPerformed
        // TODO add your handling code here:
        addCourseForm acf = new addCourseForm();
        acf.setVisible(true);
        acf.pack();
        acf.setLocationRelativeTo(null);
        acf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonAddCourse1ActionPerformed

    int rowIndex;
    private void jTableCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCoursesMouseClicked
        
        rowIndex = jTableCourses.getSelectedRow();
        //model = (DefaultTableModel)jTableCourses.getModel();
        jTextFieldManageCourseId.setText(jTableCourses.getValueAt(rowIndex,0).toString());
        jTextFieldManageCourseLabel.setText(jTableCourses.getValueAt(rowIndex,1).toString());
        jSpinnerHours.setValue(Integer.valueOf(jTableCourses.getValueAt(rowIndex,2).toString()));
        
    }//GEN-LAST:event_jTableCoursesMouseClicked

    private void jTableCoursesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCoursesKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN)
        {
            rowIndex = jTableCourses.getSelectedRow();
            jTextFieldManageCourseId.setText(model.getValueAt(rowIndex,0).toString());
            jTextFieldManageCourseLabel.setText(model.getValueAt(rowIndex,1).toString());
            jSpinnerHours.setValue(Integer.parseInt((String)model.getValueAt(rowIndex,2)));
        }
    }//GEN-LAST:event_jTableCoursesKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageCourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCourse1;
    private javax.swing.JButton jButtonDeleteCourse;
    private javax.swing.JButton jButtonEditCourse;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelManageScore;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerHours;
    public static javax.swing.JTable jTableCourses;
    private javax.swing.JTextField jTextFieldManageCourseId;
    private javax.swing.JTextField jTextFieldManageCourseLabel;
    // End of variables declaration//GEN-END:variables
}
